name               = "bergeron"
main               = ".open-next/worker.js"
workers_dev        = true
compatibility_date = "2025-05-18"
compatibility_flags = ["nodejs_compat"]
account_id = "b3e152525a8f5541cb62c7f3189b8a50"

[build]
command   = "npm run cf:build"
watch = "."

[build.upload]
format = "modules"
main   = ".open-next/cloudflare-templates/worker.js"

[assets]
directory = ".open-next/assets"
binding   = "ASSETS"